<?php

namespace Database\Seeders;

use App\Models\Kth;
use Illuminate\Database\Seeder;

class KthSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kths = [
            [
                'nama_kth' => 'KTH Lestari Makmur',
                'kelas_kth' => 'Utama',
                'nomor_register' => 'REG-001/KTH/2024',
                'tanggal_register' => '2024-01-15',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Kalianget',
                'desa' => 'Kalianget',
                'nama_ketua' => 'Slamet Riyadi',
                'no_hp_ketua' => '081234567891',
                'latitude' => -7.0567,
                'longitude' => 113.9346,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 1,
                'status_verifikasi' => 'verified',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Hijau Lestari',
                'kelas_kth' => 'Madya',
                'nomor_register' => 'REG-002/KTH/2024',
                'tanggal_register' => '2024-02-20',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Kota Sumenep',
                'desa' => 'Pabian',
                'nama_ketua' => 'Siti Aisyah',
                'no_hp_ketua' => '081234567892',
                'latitude' => -7.0123,
                'longitude' => 113.8542,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 1,
                'status_verifikasi' => 'verified',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Rimba Jaya',
                'kelas_kth' => 'Pemula',
                'nomor_register' => 'REG-003/KTH/2024',
                'tanggal_register' => '2024-03-10',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Gili Genting',
                'desa' => 'Gili Genting',
                'nama_ketua' => 'Ahmad Subandi',
                'no_hp_ketua' => '081234567893',
                'latitude' => -7.1234,
                'longitude' => 114.0456,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 2,
                'status_verifikasi' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Bina Sejahtera',
                'kelas_kth' => 'Madya',
                'nomor_register' => 'REG-004/KTH/2024',
                'tanggal_register' => '2024-04-05',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Bluto',
                'desa' => 'Bluto',
                'nama_ketua' => 'Mohammad Ali',
                'no_hp_ketua' => '081234567894',
                'latitude' => -7.0456,
                'longitude' => 113.7890,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 2,
                'status_verifikasi' => 'verified',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Mangrove Abadi',
                'kelas_kth' => 'Utama',
                'nomor_register' => 'REG-005/KTH/2023',
                'tanggal_register' => '2023-12-01',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Dungkek',
                'desa' => 'Dungkek',
                'nama_ketua' => 'Suharto',
                'no_hp_ketua' => '081234567895',
                'latitude' => -7.0789,
                'longitude' => 114.0123,
                'status_kth' => 'Tidak Aktif',
                'tahun_tidak_aktif' => 2023,
                'id_penyuluh' => 1,
                'status_verifikasi' => 'rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Tani Makmur',
                'kelas_kth' => 'Pemula',
                'nomor_register' => 'REG-006/KTH/2024',
                'tanggal_register' => '2024-05-12',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Pamekasan',
                'desa' => 'Pamekasan',
                'nama_ketua' => 'Sutrisno',
                'no_hp_ketua' => '081234567896',
                'latitude' => -7.2345,
                'longitude' => 113.6789,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 2,
                'status_verifikasi' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Sumber Rejeki',
                'kelas_kth' => 'Madya',
                'nomor_register' => 'REG-007/KTH/2024',
                'tanggal_register' => '2024-06-20',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Gapura',
                'desa' => 'Gapura',
                'nama_ketua' => 'Muhammad Fahrur',
                'no_hp_ketua' => '081234567897',
                'latitude' => -7.0567,
                'longitude' => 113.9012,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 1,
                'status_verifikasi' => 'verified',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Harapan Baru',
                'kelas_kth' => 'Pemula',
                'nomor_register' => 'REG-008/KTH/2024',
                'tanggal_register' => '2024-07-15',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Batuputih',
                'desa' => 'Batuputih',
                'nama_ketua' => 'Junaidi',
                'no_hp_ketua' => '081234567898',
                'latitude' => -7.0890,
                'longitude' => 113.8345,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 2,
                'status_verifikasi' => 'pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Alam Lestari',
                'kelas_kth' => 'Utama',
                'nomor_register' => 'REG-009/KTH/2023',
                'tanggal_register' => '2023-11-20',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Ganding',
                'desa' => 'Ganding',
                'nama_ketua' => 'Abdul Manan',
                'no_hp_ketua' => '081234567899',
                'latitude' => -7.0123,
                'longitude' => 113.7234,
                'status_kth' => 'Tidak Aktif',
                'tahun_tidak_aktif' => 2023,
                'id_penyuluh' => 1,
                'status_verifikasi' => 'rejected',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_kth' => 'KTH Rimba Hijau',
                'kelas_kth' => 'Madya',
                'nomor_register' => 'REG-010/KTH/2024',
                'tanggal_register' => '2024-08-25',
                'kabupaten' => 'Sumenep',
                'kecamatan' => 'Banyuates',
                'desa' => 'Banyuates',
                'nama_ketua' => 'Karsono',
                'no_hp_ketua' => '081234567900',
                'latitude' => -7.0567,
                'longitude' => 113.4567,
                'status_kth' => 'Aktif',
                'tahun_tidak_aktif' => null,
                'id_penyuluh' => 2,
                'status_verifikasi' => 'verified',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($kths as $kth) {
            Kth::create($kth);
        }
    }
}