<?php

namespace Database\Seeders;

use App\Models\Penyuluh;
use Illuminate\Database\Seeder;

class PenyuluhNewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $penyuluhs = [
            [
                'user_id' => 16,
                'nama_lengkap' => 'Dr. Ir. Slamet Riyadi, M.Si',
                'nip' => '197501011999031001',
                'golongan_pangkat' => 'IV/b - Pembina Tk I',
                'nik' => '3529010101750001',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1975-01-01',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Trunojoyo No. 45, Sumenep',
                'no_telepon' => '081234567890',
                'email_pribadi' => 'slamet.riyadi@gmail.com',
                'jabatan' => 'Koordinator Penyuluh Kehutanan',
                'wilayah_kerja' => 'Sumenep Selatan',
            ],
            [
                'user_id' => 17,
                'nama_lengkap' => 'Ir. Siti Aisyah, M.P',
                'nip' => '197803151999032002',
                'golongan_pangkat' => 'IV/a - Pembina',
                'nik' => '3529011531978002',
                'tempat_lahir' => 'Pamekasan',
                'tanggal_lahir' => '1978-03-15',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Diponegoro No. 12, Sumenep',
                'no_telepon' => '081234567891',
                'email_pribadi' => 'siti.aisyah@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Ahli Madya',
                'wilayah_kerja' => 'Sumenep Utara',
            ],
            [
                'user_id' => 18,
                'nama_lengkap' => 'Drs. Ahmad Subandi, S.Hut',
                'nip' => '198005101999031003',
                'golongan_pangkat' => 'III/d - Penata Tk I',
                'nik' => '3529011051980003',
                'tempat_lahir' => 'Bangkalan',
                'tanggal_lahir' => '1980-05-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Kartini No. 78, Sumenep',
                'no_telepon' => '081234567892',
                'email_pribadi' => 'ahmad.subandi@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Ahli Muda',
                'wilayah_kerja' => 'Kecamatan Kalianget',
            ],
            [
                'user_id' => 19,
                'nama_lengkap' => 'Ir. Mohammad Ali, M.M',
                'nip' => '198207202000031004',
                'golongan_pangkat' => 'III/c - Penata',
                'nik' => '3529012071982004',
                'tempat_lahir' => 'Sampang',
                'tanggal_lahir' => '1982-07-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Ahmad Yani No. 34, Sumenep',
                'no_telepon' => '081234567893',
                'email_pribadi' => 'mohammad.ali@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Lanjutan',
                'wilayah_kerja' => 'Kecamatan Bluto',
            ],
            [
                'user_id' => 20,
                'nama_lengkap' => 'Dra. Suharto, M.Si',
                'nip' => '198410152000032005',
                'golongan_pangkat' => 'III/c - Penata',
                'nik' => '3529011541984005',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1984-10-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Raya Sumenep No. 56',
                'no_telepon' => '081234567894',
                'email_pribadi' => 'suharto@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Ahli Muda',
                'wilayah_kerja' => 'Kecamatan Dungkek',
            ],
            [
                'user_id' => 21,
                'nama_lengkap' => 'Ir. Sutrisno, M.P',
                'nip' => '198601052001031006',
                'golongan_pangkat' => 'III/b - Penata Muda Tk I',
                'nik' => '3529011051986006',
                'tempat_lahir' => 'Pamekasan',
                'tanggal_lahir' => '1986-01-05',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Veteran No. 89, Sumenep',
                'no_telepon' => '081234567895',
                'email_pribadi' => 'sutrisno@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana',
                'wilayah_kerja' => 'Kecamatan Gapura',
            ],
            [
                'user_id' => 22,
                'nama_lengkap' => 'Dra. Siti Aisyah, S.Hut',
                'nip' => '198703152001032007',
                'golongan_pangkat' => 'III/b - Penata Muda Tk I',
                'nik' => '3529011531987007',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1987-03-15',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Pahlawan No. 23, Sumenep',
                'no_telepon' => '081234567896',
                'email_pribadi' => 'siti.aisyah2@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Lanjutan',
                'wilayah_kerja' => 'Kecamatan Batuputih',
            ],
            [
                'user_id' => 23,
                'nama_lengkap' => 'Drs. Muhammad Fahrur, M.Si',
                'nip' => '198806102002031008',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011071988008',
                'tempat_lahir' => 'Bangkalan',
                'tanggal_lahir' => '1988-06-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. HOS Cokroaminoto No. 67, Sumenep',
                'no_telepon' => '081234567897',
                'email_pribadi' => 'fahrur.muhammad@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana',
                'wilayah_kerja' => 'Kecamatan Ganding',
            ],
            [
                'user_id' => 24,
                'nama_lengkap' => 'Ir. Junaidi, S.Hut',
                'nip' => '199010152003031009',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011511990009',
                'tempat_lahir' => 'Sampang',
                'tanggal_lahir' => '1990-10-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Sudirman No. 45, Sumenep',
                'no_telepon' => '081234567898',
                'email_pribadi' => 'junaidi@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Pemula',
                'wilayah_kerja' => 'Kecamatan Banyuates',
            ],
            [
                'user_id' => 25,
                'nama_lengkap' => 'Dra. Karsono, M.Pd',
                'nip' => '199203202004031010',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011531992010',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1992-03-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Imam Bonjol No. 12, Sumenep',
                'no_telepon' => '081234567899',
                'email_pribadi' => 'karsono@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Pemula',
                'wilayah_kerja' => 'Kecamatan Kota Sumenep',
            ],
            [
                'user_id' => 26,
                'nama_lengkap' => 'Ir. Bambang Wibowo, M.Si',
                'nip' => '197506151999031011',
                'golongan_pangkat' => 'IV/a - Pembina',
                'nik' => '3529011561975011',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1975-06-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pahlawan No. 88, Sumenep',
                'no_telepon' => '081234567800',
                'email_pribadi' => 'bambang.wibowo@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Ahli Madya',
                'wilayah_kerja' => 'Kecamatan Kalianget',
            ],
            [
                'user_id' => 27,
                'nama_lengkap' => 'Dra. Dewi Kartika, M.P',
                'nip' => '197908202000032012',
                'golongan_pangkat' => 'III/d - Penata Tk I',
                'nik' => '3529011521979012',
                'tempat_lahir' => 'Pamekasan',
                'tanggal_lahir' => '1979-08-20',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Diponegoro No. 33, Sumenep',
                'no_telepon' => '081234567801',
                'email_pribadi' => 'dewi.kartika@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Ahli Muda',
                'wilayah_kerja' => 'Kecamatan Bluto',
            ],
            [
                'user_id' => 28,
                'nama_lengkap' => 'Drs. Agus Santoso, S.Hut',
                'nip' => '198104102001031013',
                'golongan_pangkat' => 'III/c - Penata',
                'nik' => '3529011101981013',
                'tempat_lahir' => 'Bangkalan',
                'tanggal_lahir' => '1981-04-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Kartini No. 55, Sumenep',
                'no_telepon' => '081234567802',
                'email_pribadi' => 'agus.santoso@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Lanjutan',
                'wilayah_kerja' => 'Kecamatan Dungkek',
            ],
            [
                'user_id' => 29,
                'nama_lengkap' => 'Ir. Rina Marlina, M.M',
                'nip' => '198306252002032014',
                'golongan_pangkat' => 'III/c - Penata',
                'nik' => '3529011531983014',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1983-06-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Ahmad Yani No. 77, Sumenep',
                'no_telepon' => '081234567803',
                'email_pribadi' => 'rina.marlina@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Ahli Muda',
                'wilayah_kerja' => 'Kecamatan Gapura',
            ],
            [
                'user_id' => 30,
                'nama_lengkap' => 'Dra. Budi Santoso, M.Si',
                'nip' => '198509012001031015',
                'golongan_pangkat' => 'III/b - Penata Muda Tk I',
                'nik' => '3529011051985015',
                'tempat_lahir' => 'Sampang',
                'tanggal_lahir' => '1985-09-01',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Raya Sumenep No. 22, Sumenep',
                'no_telepon' => '081234567804',
                'email_pribadi' => 'budi.santoso@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana',
                'wilayah_kerja' => 'Kecamatan Batuputih',
            ],
            [
                'user_id' => 31,
                'nama_lengkap' => 'Ir. Eko Prasetyo, M.P',
                'nip' => '198712152002031016',
                'golongan_pangkat' => 'III/b - Penata Muda Tk I',
                'nik' => '3529011521987016',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1987-12-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Veteran No. 99, Sumenep',
                'no_telepon' => '081234567805',
                'email_pribadi' => 'eko.prasetyo@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Lanjutan',
                'wilayah_kerja' => 'Kecamatan Ganding',
            ],
            [
                'user_id' => 32,
                'nama_lengkap' => 'Dra. Fitri Handayani, S.Hut',
                'nip' => '198902202003032017',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011531989017',
                'tempat_lahir' => 'Pamekasan',
                'tanggal_lahir' => '1989-02-20',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. HOS Cokroaminoto No. 44, Sumenep',
                'no_telepon' => '081234567806',
                'email_pribadi' => 'fitri.handayani@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana',
                'wilayah_kerja' => 'Kecamatan Banyuates',
            ],
            [
                'user_id' => 33,
                'nama_lengkap' => 'Drs. Gatot Subroto, M.Si',
                'nip' => '199105052003031018',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011051991018',
                'tempat_lahir' => 'Bangkalan',
                'tanggal_lahir' => '1991-05-05',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Sudirman No. 66, Sumenep',
                'no_telepon' => '081234567807',
                'email_pribadi' => 'gatot.subroto@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Pemula',
                'wilayah_kerja' => 'Kecamatan Kota Sumenep',
            ],
            [
                'user_id' => 34,
                'nama_lengkap' => 'Ir. Hesti Wahyuni, M.M',
                'nip' => '199307152004031019',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011531993019',
                'tempat_lahir' => 'Sumenep',
                'tanggal_lahir' => '1993-07-15',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Imam Bonjol No. 88, Sumenep',
                'no_telepon' => '081234567808',
                'email_pribadi' => 'hesti.wahyuni@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Pemula',
                'wilayah_kerja' => 'Kecamatan Kalianget',
            ],
            [
                'user_id' => 35,
                'nama_lengkap' => 'Dra. Indra Setiawan, M.Pd',
                'nip' => '199501202004031020',
                'golongan_pangkat' => 'III/a - Penata Muda',
                'nik' => '3529011511995020',
                'tempat_lahir' => 'Sampang',
                'tanggal_lahir' => '1995-01-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pahlawan No. 11, Sumenep',
                'no_telepon' => '081234567809',
                'email_pribadi' => 'indra.setiawan@gmail.com',
                'jabatan' => 'Penyuluh Kehutanan Pelaksana Pemula',
                'wilayah_kerja' => 'Kecamatan Bluto',
            ],
        ];

        foreach ($penyuluhs as $data) {
            Penyuluh::create($data);
        }
    }
}